- .stylelintrc.json
- src/components/BaseStyles/globals.module.css
- src/components/BaseStyles/index.ts
- src/components/BaseStyles/package.json
To prevent duplicate styles, a shared base styles package should be available for all components to depend on.
The globals.module.css contains the styles as defined in the [Design Systems identity](https://www.figma.com/file/JpoY3waVoQGlLQzQXTL9nn/Design-System---Gemeente-Den-Haag?node-id=43%3A338)
> Add base styles package

- src/components/BaseProps/src/index.tsx
- src/components/IconButton/src/index.tsx
This might not be something we want to expose like this, but tabIndex is necessary for the design implementation for list.
> Added the tabindex property to IconButton

- .github/ISSUE_TEMPLATE/feature_request.md
- .github/dependabot.yml
- .github/workflows/cicd.yml
This PR updates the github configuration files (such as `cicd.yaml` and dependabot) to respect the new branching strategy, which removes the development branch.
Closes #199 Remove dev branch
> Update github configs to use master branch instead of development

- .github/workflows/cicd.yml
- .husky/post-merge
- README.md
I noticed we had a lot of issues with situations that were not easy to reproduce across machines and a lot of "works on my machine" situations. This PR changes the yarn installation command to use the exact versions that were tested in the PR that updated the dependencies.
Since this repository uses Dependabot to stay up to date with the latest versions of dependencies (and incidentally the test scripts of GitHub Actions will test if the upgrade would break anything) there should be no need to rely on the flexible version ranges (`^1.0.0` and `~1.0.0`) in the `package.json` file.
> Reproducible builds using exact version from Yarn lockfile

- src/components/Button/src/index.tsx
The onClick function in the ButtonProps interface has no type. React provides [Synthetic events](https://reactjs.org/docs/events.html) that wrap around native browser events. This PR allows users to access a MouseEvent.
closes #103 Button OnClick prop type is incorrect
> Add type to onClick function in ButtonProps

- .eslintrc
- src/components/Accordion/src/Accordion.stories.tsx
- src/components/Accordion/src/Accordion.tsx
- src/components/FormControlLabel/src/index.tsx
- src/components/List/src/List.tsx
- src/components/List/src/ListItem.tsx
- src/components/List/src/ListItemAvatar.tsx
- src/components/Menu/src/Popover.tsx
- src/components/Menu/src/Popper.tsx
- src/components/Pickers/src/BaseDatePickerProps/BaseDatePickerProps.tsx
- src/components/Pickers/src/DatePicker.stories.tsx
- src/components/Pickers/src/DatePicker/DatePicker.tsx
- src/components/Pickers/src/KeyBoardDatePicker.stories.tsx
- src/components/Pickers/src/KeyboardDatePicker/KeyboardDatePicker.tsx
- src/components/PickersUtilsProvider/src/index.tsx
- src/components/Radio/src/Radio.tsx
- src/components/Radio/src/RadioGroup.tsx
- src/components/Radio/src/stories/Radio.stories.tsx
- src/components/Select/src/index.tsx
- src/components/Stepper/src/StepContent.tsx
- src/components/Tab/src/Tab.tsx
- src/components/Tab/src/Tabs.tsx
- src/components/TextField/src/BaseTextFieldProps.ts
- src/components/TextField/src/index.tsx
closes #152 
Enabled any error in eslint, and fixed/reworked all cases where any was used.
In most cases the MUI type could be copied 1:1.
In other cases the most commonly used types were chosen (e.g. value for tab).
If there was no obviously commonly used type and MUI uses any in their docs,
I added a disable warning comment and left it as any.
In some cases the type was too complex or deeply nested to figure out (e.g. Popover), 
in that case I chose to use the type used in the Material properties.
This should work in the current state, and once we refactor these components we can revisit them.
> Introduced disallow any rule

- .stylelintignore
- .stylelintrc.json
- src/components/Button/src/button.module.css
Since sometimes the following properties are included in the codebase, even though they are not widely supported by browsers, I suggest to include linting rules to warn against their usage:
https://github.com/Gemeente-DenHaag/denhaag-component-library/pull/134#discussion_r648057710
- [`margin-block`](https://caniuse.com/?search=margin-block)
- [`margin-inline`](https://caniuse.com/?search=margin-inline)
- [`padding-block`](https://caniuse.com/?search=padding-block)
- [`padding-inline`](https://caniuse.com/?search=padding-inline)
> Prevent logical spacing shorthands

- src/components/DotIndicator/README.md
- src/components/DotIndicator/package.json
- src/components/DotIndicator/src/dot-indicator.css
- src/components/DotIndicator/src/index.tsx
- src/components/DotIndicator/src/stories/DotIndicator.stories.mdx
- src/components/DotIndicator/tsconfig.json
- src/styles/Components/src/denhaag/dot-indicator/block.style-dictionary.json
This PR adds the Dot Indicator component (figma) #62 . The dot indicator is required for the counter badge. 
Remaining todos:
> Dot indicator

- src/components/Timeline/src/styles/step.css
- src/styles/Components/src/denhaag/timeline/element-modifier.style-dictionary.json
Timeline styling is broken in staging due to a missing token after migrating to style-dictionary.
http://dhreactstorybook-staging.azurewebsites.net/?path=/story/components-navigation-timeline--default
Should be
> Fix timeline missing design token

- .storybook/main.js
- .storybook/preview.js
- package.json
- style-dictionary.config.json
- yarn.lock
Replace "light" and "dark" toolbar button with full-fledged theme switcher addon.
https://github.com/tonai/storybook-addon-themes
To make this work, the design tokens should always not be available on `:root` but be provided via a theme class name instead.
I have added an additional file to the Style Dictionary output, `theme/index.css`, that provides all the design tokens for the `.denhaag-theme` class name.
> Storybook theme switcher and Style Dictionary theme output

- .storybook/preview.js
- src/components/Button/src/index.tsx
- src/components/Card/src/Card/Card.tsx
- src/components/Divider/src/index.tsx
- src/components/IconButton/src/index.tsx
- src/components/List/src/List.tsx
- src/components/StylesProvider/package.json
- src/components/StylesProvider/src/index.tsx
- src/components/StylesProvider/tsconfig.json
- src/components/Timeline/src/StepContent.tsx
- src/components/Timeline/src/StepIcon.tsx
- src/meta-packages/denhaag-component-library/package.json
- src/meta-packages/denhaag-component-library/src/index.tsx
Instead of wrapping every MUI based component with StylesProvider individually, I added a decorator that wraps it for every story.
In the react app, we should then enforce the CSS to be loaded in the correct order.
The easiest way is to do this with StylesProvider in the client and wrapping the whole app in 
`<StyleProvider injectFirst>`
Related links:
https://material-ui.com/styles/advanced/#injectfirst
https://www.sipios.com/blog-tech/how-to-use-styled-components-with-material-ui-in-a-react-app
closes #288
> Fixing MUI stylesProvider warning

- src/components/Link/src/Link.stories.mdx
- src/components/Link/src/index.tsx
- src/components/Link/src/link.css
FIxes the alignment for icons in the Link component.
Bit of a dirty fix imo but due to the padding on the block for the focus border and the icon being higher than the line-height. 
closes #330
> fix: fixed alignment of icon for link component

- .github/workflows/cicd.yml
This PR updates the pipeline to deploy to github pages instead of an azure web app. 
**Changes**
- Use GitHub Pages instead of Azure Websites
- Remove staging / production steps and only deploy from master
Uses Github Action: https://github.com/JamesIves/github-pages-deploy-action
> ci: update deployment to use github pages

- src/meta-packages/navigation/src/index.tsx
This PR adds the `Link` component to the exported components in the `@gemeente-denhaag/navigation` meta-package.
closes #386
> Link: not exported from component library

- .ncurc.major.js
- .ncurc.minor.js
- .ncurc.patch.js
- CONTRIBUTING.md
- package.json
- yarn.lock
Having the `npm-check-updates` plugin can make it easier to install updates suggested by Dependabot, avoid merge conflicts in those PRs, and avoid updating only one package at the time instead of updating a whole bunch of related packages (`@storybook/...-addon` for example).
> ci: add npm-check-updates

- components/Breadcrumb/src/breadcrumb.css
Fix for the recently approved and merged breadcrumbs HTML and CSS component.
Without:
With fix:
> fix(breadcrumb): added minor fix for the separator after an icon

- components/Alert/specs/Alert.spec.jsx
Quick PR removing a11y check disables in the Alert component tests. These issues have already been resolved in #406 and #407, but we never removed the rule disables, resulting in these properties not being checked and warnings in the GH Actions Annotations (see screenshot).
> fix: removed alert component a11y check disables

- components/Accordion/src/index.scss
- components/Accordion/src/stories/bem.stories.mdx
- components/BadgeCounter/package.json
- components/BadgeCounter/src/index.scss
- components/BadgeCounter/src/index.tsx
- components/BadgeCounter/src/stories/bem.stories.mdx
- components/Button/src/index.scss
- components/IconButton/src/index.scss
- components/PublicationDate/src/index.scss
- package.json
- proprietary/Common/src/denhaag/focus.tokens.json
- proprietary/Components/src/denhaag/accordion.tokens.json
- proprietary/Components/src/denhaag/button.tokens.json
- proprietary/Components/src/denhaag/card.tokens.json
- proprietary/Components/src/denhaag/cta-download.tokens.json
- proprietary/Components/src/denhaag/cta-event.tokens.json
- proprietary/Components/src/denhaag/cta-link.tokens.json
- proprietary/Components/src/denhaag/datepicker.tokens.json
- proprietary/Components/src/denhaag/publication-date.tokens.json
- proprietary/Proprietary/src/typography.tokens.json
- yarn.lock
> Design update: font-size, focus, padding

- proprietary/Components/src/denhaag/table.tokens.json
`closes #763 `
font-weight bug fix and removed value because we don't do that anymore.
> fix: new syntax and correct font-weight value

- components/Typography/src/paragraph.scss
`closes #761 `
`--denhaag-paragraph-color` is undefined.   `--utrecht-paragraph-color` has the correct grey/4 color.
> fix: from --denhaag-paragraph-color to --utrecht-paragraph-color

- components/CtaImageContent/src/index.scss
Solve:
https://github.com/nl-design-system/denhaag/issues/810
Purpose:
- preventing the image from sticking out of the border radius
closes #811
> style(cta-image-content): add styling correction

- components/OrderedList/src/index.scss
Solve: https://github.com/nl-design-system/denhaag/issues/814
Purpose:
- add fallback styling for child list of ordered list
closes #815
> style(ordered-list): add fallback styling nested list

- components/FormProgress/package.json
- components/FormProgress/specs/FormProgress.spec.jsx
- components/FormProgress/specs/__snapshots__/FormProgress.spec.jsx.snap
- components/FormProgress/src/index.scss
- components/FormProgress/src/index.tsx
- components/FormProgress/src/stories/bem.stories.mdx
- components/FormProgress/src/stories/react.stories.mdx
- components/FormProgress/tsconfig.json
- packages/components-react/src/index.tsx
- proprietary/Components/src/denhaag/form-progress.tokens.json
- tsconfig.json
@bddjong a few questions about this solution, could you look at these once you have the time?
- Not sure about this label setup, feels quite annoying to have there `stepLabel` and `ofLabel` props. Any ideas on how to fix this nicely? I considered using perhaps some sort of format string a la python (e.g. `label="Stap {0} van {1}") in a label prop, or alternatively just provide one `label` prop with no formatting whatsoever and let the end-user deal with it, but curious whether you have any thoughts on this.
- the `htmlFor` and `id` on the `label` and `progress` are currently static, resulting in invalid HTML/duplicate id's when the component is used multiple times. 
- Closes #728
> FormProgress Component

- proprietary/Components/src/denhaag/authentication-block.tokens.json
Renamed token, since value was ignored.
> fix(authentication-block-token): set correct token name

- components/AnchorNavigation/src/index.scss
- proprietary/Components/src/denhaag/anchor-navigation.tokens.json
Removing spacing at link-items, otherwise u get gutter stacked on the inline padding. When the component is already rendered 2 columns, this decreases the readability a lot.
closes #857
> fix(anchor-navigation): remove spacing after link

- components/AnchorNavigation/src/index.scss
Solve: https://github.com/nl-design-system/denhaag/issues/866
Purpose:
Only show outline with tab key.
closes   #867
> style(anchor-navigation): add only link focus on tab key

- components/Hero/src/index.scss
- proprietary/Components/src/denhaag/hero.tokens.json
Remove overflow-hidden. Not needed anymore since there aren't any SVG patterns added.
Currently it's only causing issues (with searchbox)
> fix(hero-overflow): remove overflow properties, since they're redundant

- components/HighlightedLinks/package.json
- components/Subnavigation/README.md
- components/Subnavigation/package.json
- components/Subnavigation/src/Sidenav.tsx
- components/Subnavigation/src/SidenavItem.tsx
- components/Subnavigation/src/SidenavLink.tsx
- components/Subnavigation/src/SidenavList.tsx
- components/Subnavigation/src/index.scss
- components/Subnavigation/src/index.tsx
- components/Subnavigation/src/stories/bem.stories.mdx
- components/Subnavigation/src/stories/react.stories.mdx
- components/Subnavigation/tsconfig.json
- proprietary/Components/src/denhaag/sidenav.tokens.json
Adds the sidenav component as seen in the portal libraries. Design tokens and BEM naming copied from `utrecht-sidenav` with a few changes to the design tokens.
> feat: add sidenav component

- rollup.config.js
TLDR: my new approach (that replaces #907) is simply to build the CSS from rollup too, just like the build for `@gemeente-denhaag/components-css` already does. Since not every package has CSS files, I included a filter to check if the input actually exists, and just skip the build step otherwise.
---
An alternative approach was needed, compared to PR #907, to separately provide `dist/index.css` for every component that has CSS. My previous approach used command line `sass`, but importing CSS from `node_modules/` works differently in `sass` than in 
The `~` in `import "~@utrecht/components"` was giving me headaches: rollup requires it because [`rollup-plugin-postcss`](https://github.com/egoist/rollup-plugin-postcss#imports) has quite a simplistic resolving heuristic for references that …
> build: separate build target for component CSS

- components/Typography/src/stories/heading2.bem.stories.mdx
- components/Typography/src/stories/heading3.bem.stories.mdx
- components/Typography/src/stories/heading4.bem.stories.mdx
- components/Typography/src/stories/heading5.bem.stories.mdx
- proprietary/Components/src/utrecht/heading-2.tokens.json
- proprietary/Components/src/utrecht/heading-3.tokens.json
- proprietary/Components/src/utrecht/heading-4.tokens.json
- proprietary/Components/src/utrecht/heading-5.tokens.json
Solve: headings tokens empty
Purpose: 
- re-add the tokens
- some bem corrections, the right html heading tags
closes #943
> style(GDH-407): re-add tokens for headings

- components/CtaImageContent/src/index.scss
- proprietary/Components/src/denhaag/cta-image-content.tokens.json
Set cursor of cta-image-content button to a pointer instead of defautl arrow on request of accessibility expert.
> style(cta-content-image): fix accessibility issue with button style

- components/Breadcrumb/src/index.scss
Solve: https://acato-nl.atlassian.net/browse/GDH-435
Purpose:
- enable text in breadcrumb to wrap (reponsive)
closes #952
> style(breadcrumb): add styling correction enable text wrap

- components/CardNews/src/index.scss
- components/CardNews/src/stories/bem.stories.mdx
- components/CardNews/src/storybook.scss
- proprietary/Components/src/denhaag/card-news.tokens.json
**GDH-507:**
Edit HTML of the card, for accessibility screenreaders.
Link must only be inside of the heading, removing the figcaption.
**See ticket below:**
> On the homepage, under 'News items', there are cards that are formatted in a separate way: with figure and figcaption.
>
> Figure/figcaption are primarily intended to semantically link a caption and an image. (By the way, the image must have a filled alt attribute, otherwise you will have a caption of a non-existent image.)
>
> When a screen reader encounters a figure/figcaption, it indicates it with: 'grouping', 'caption'.
>
> But as it is now intended, this is not an image/caption relationship, but a 'simple' card:
>
> Steps to reproduce:
>
> View the source code of the news items.
>
> Result:
>
> A screen reader (in this case …
> refactor(card-news): refactor due to accessibility feedback

- components/List/src/List.tsx
- components/List/src/ListItem.tsx
- components/List/src/ListItemIcon.tsx
- components/List/src/ListItemSecondaryAction.tsx
- components/List/src/ListItemText.tsx
- components/List/src/ListSubheader.tsx
In the List component, `props.className` was not properly passed to the underlying component. This PR fixes this by adding it to the `clsx` parameters
> fix(list): add className prop support

- components/CardNews/src/index.scss
Fixed the focus style after te accessibility refactor where the `<a>` element should only be wrapped around the Title instead of the whole card.
> style(card-news): fix focus styles after refactor

- components/Icons/src/SvgIcon.tsx
While using components like `FormProgress` and `Datepicker` in our demo apps I'm getting an error about the Icons as they are using the `shape-rendering` property in React. I assume other people will run into the same issue and think its super simple to use `shapeRendering` instead ☺️
I went rogue and didn't create an issue as I think it's a super simple fix. @bddjong @mjcarsjens what do you prefer? Is this PR good enough or should I still create an issue for it?
> fix: use react supported shapeRendering instead of shape-rendering

- components/Link/src/index.scss
Ticket: https://acato-nl.atlassian.net/browse/GDH-610
Solving:
- vertical alignment of arrows in a list item
- horizontal space between arrow and text in a list item
Explanation:
I put it in a seperate list selector, because putting the css properties directly into the `.denhaag-link__icon` gave the vertical alignment of the link in the paragraph a different vertical alignment.
closes #991
> style(link-with-icon): add arrow alignment link icon in list item

- components/FloatingContact/src/FloatingContact.js
- components/FloatingContact/src/stories/bem.stories.mdx
Ticket: https://acato-nl.atlassian.net/browse/GDH-58
Solve
When the foldout is open, close it: 
- If you tab out of the fold-out (so if you tap away from 'info@denhaag.nl'); 
- If you shift-tab from the 'Contact' button; 
- With ESC.
https://user-images.githubusercontent.com/95216123/173815058-49af1ad1-100c-4a84-9825-d69237e36128.mov
closes #990
> fix(floating contact): added keyboard events

- components/LinkGroup/src/index.scss
- proprietary/Components/src/denhaag/link-group.tokens.json
Solve: https://acato-nl.atlassian.net/browse/GDH-610
Figma: https://www.figma.com/file/JpoY3waVoQGlLQzQXTL9nn/Design-System---Gemeente-Den-Haag?node-id=1485%3A1156
Purpose:
- link group arrow size correction
Before:
After:
closes  #1000
> style(link-group): change arrow size

- components/Link/src/index.scss
- components/Link/src/stories/bem.stories.mdx
Solve: there still was clutter in the bem + css files (unused css selectors)
Purpose:
- remove unused css selectors in bem file
- remove unused css selectors in css file
closes #1020
> refactor(link): cleanup unused css selectors

- components/CtaImageContent/src/stories/bem.stories.mdx
--Quote Fernand van Olphen (accessibility The Hague):
Figure and figcaption are elements that are not necessary for accessibility.
We have decided not to give the image in this component alternative text.
A figcaption is an element that is used to complement the figure element.
It says something extra about what is in the figure element.
But since the image has no alternative text, the figcaption complements... nothing.
- accessibility
closes #1031
> refactor(cta-image-content): change figure + figcaption

- components/FloatingContact/src/FloatingContact.js
- components/FloatingContact/src/stories/bem.stories.mdx
Applying feedback of Fernand (accessibility expert): Removing the label-update due to an accessibility issue which will occur for screenreader
Example screenreader old way:
- Open contact;
- Close Close;
Example screenreader new way:
- Open contact;
- Close contact;
> feat(floating-contact): remove label change on click

- components/LinkGroup/src/index.scss
- proprietary/Components/src/denhaag/link-group.tokens.json
Fixing issue where padding was used, causing the image to shrink instead of applying whitespace below the image.
Sadly the important is needed, otherwise the H3 margin-block-start overrules the caption style.
> fix(link-group): fix image, apply margin instead of padding

- components/FloatingContact/src/index.scss
- components/FloatingContact/src/stories/bem.stories.mdx
Ticket: https://acato-nl.atlassian.net/browse/GDH-710
- Applied fix for the 400% zoom issue;
- Applied story with modifier;
- Fix typo;
- Also apply fix for duplicate H2, where only one is needed to be shown when zoomed;
- Direct `mailto:` to a normal link;
> style(floating-contact): fix zoom issue on 400%

- components/Accordion/src/index.scss
- components/Accordion/src/stories/bem.stories.mdx
- proprietary/Components/src/denhaag/accordion.tokens.json
wrong/not up-to-date styling https://acato-nl.atlassian.net/browse/GDH-665
correct font-size, font-weight, font-family and color for accorion panel titles
- closed and opened: font-size 18px, font-family TheSans
- when closed: default (font-weight 400), hover (font-weight 400, color green 3) and focus (font-weight 400, color green 3)
- when opened: default (font-weight 700 ,color green 3), hover (font-weight 700, color green 4) and focus (font-weight 700, color green 3)
- overhaul/refactor of bem, css and tokens.
- added 'open', 'open - hover' and 'open - focus' bem for more clearity in styling
https://www.figma.com/file/JpoY3waVoQGlLQzQXTL9nn/Design-System---Gemeente-Den-Haag?node-id=1585%3A0
closes #1041
> style(accordion): styling corrections panel titles

- components/Table/src/TableRow.tsx
- components/Table/src/stories/bem.stories.mdx
- suggestion there is any action on the table row (when ther isn't any) tabbing with keyboard focus
- cleanup the tabindex on the table rows, so suggestion of action is removed
closes #1044
> fix(table): remove tabindex for accessibility

- components/DynamicContent/src/index.scss
Add flex-wrap due to grid issues:
**Before**
**After**
> style(dynamic-content): add flex-wrap due grid-breaking issues

- README.md
for providing us with a free starter plan of 35k snapshots each month in addition to our own paid license.
> docs: credit chromatic

- components/CtaLink/src/index.scss
- components/CtaLink/src/stories/bem.stories.mdx
to align it with the [Figma designs](https://www.figma.com/file/JpoY3waVoQGlLQzQXTL9nn/Design-System---Gemeente-Den-Haag?node-id=8105%3A21885)
and to prevent weird whitespace and wrap issues
> fix: remove flexbox logic from .denhaag-cta-link__excerpt

- components/Hero/src/index.scss
- components/Typography/src/heading.scss
Headings didn't get any color or line-height css line. Also all values were equal, therefor a change for all header-classes and an update for the hero which used the old heading token.
> style(heading): set color for heading and remove unset tokens

- components/DynamicContent/src/index.scss
- proprietary/Components/src/denhaag/dynamic-content.tokens.json
Words that should be broken but aren't broken causing issues with the flex-layout.
**Before:**
**After:**
Another issue (i already mentioned this to design) is that it's designed for 1/2 lines of text and now whole paragraphs are provided.
> fix(dynamic-content): fix for text breaking layout

- components/Image/src/index.scss
- proprietary/Components/src/denhaag/image.tokens.json
Solve:
- old uppercase image caption
Purpose:
- change to new non text-transform, a.k.a. the default text without transform
Figma: https://www.figma.com/file/JpoY3waVoQGlLQzQXTL9nn/Design-System---Gemeente-Den-Haag?node-id=8553%3A29678
closes #1076
> style(image): remove uppercase img caption

- components/Accordion/src/index.scss
Fixing the click action on the icon. Since it had the default pointer-events, clicking on the icon wouldn't toggle the accordion-item.
> fix(accordion-item): fix click action on icon

- components/Button/src/index.scss
- components/Button/src/stories/bem.stories.mdx
- proprietary/Components/src/denhaag/button.tokens.json
- new button icon only missing
- add icon only buttons, bem + css
- icon only, arrow right: https://www.figma.com/file/JpoY3waVoQGlLQzQXTL9nn/Design-System---Gemeente-Den-Haag?node-id=1%3A656
- icon only, horizontal scroll buttons (for mobile table): https://www.figma.com/file/JpoY3waVoQGlLQzQXTL9nn/Design-System---Gemeente-Den-Haag?node-id=5213%3A16235 
closes #1078
> feat(button): add icon only buttons

- components/Button/src/index.scss
- proprietary/Components/src/denhaag/button.tokens.json
- incorrect button icon-only height and width
- height and width correction of button icon-only variant
Figma: https://www.figma.com/file/JpoY3waVoQGlLQzQXTL9nn/Design-System---Gemeente-Den-Haag?node-id=1%3A656
closes #1080
> fix(button): style correction btn icon-only

- components/Image/src/index.scss
- proprietary/Components/src/denhaag/image.tokens.json
- outdated image caption style (letter-spacing)
- figma: https://www.figma.com/file/JpoY3waVoQGlLQzQXTL9nn/Design-System---Gemeente-Den-Haag?node-id=8553%3A29678
- update image caption style (remove letter-spacing)
closes #1085
> style(image): remove letter-spacing

- components/DynamicContent/package.json
- components/Image/package.json
- components/Table/package.json
Solve:
- npm publish tags are not up-to-date, so when updating packages (@gemeente-denhaag/components-css, @gemeente-denhaag/design-tokens-common and @gemeente-denhaag/design-tokens-components) in another project, they still get the old tags/npm publish dates/versions
Purpose:
- update package versions, so the npm publish tags will be hopefully updated
closes #1089
> docs(release): update package versions

- .github/workflows/cicd.yml
for pushing CI-bot commits like version number to main without checks
> ci: add github-admin-token

- components/Typography/src/heading.scss
- proprietary/Proprietary/src/typography.tokens.json
- headings on mobile are to big
- font-family for headings is not the correct one
- add mobile headings font-sizes
- change headings font-family to theMix
- https://www.figma.com/file/fCCe3DA2gCfsqYOm0vuPsi/Final-UI---Transitie-Online?node-id=7416%3A91424
closes #1092
> style(typography): change font-family, mobile font-sizes

- components/DynamicContent/src/index.scss
Fix issue for Chrome for windows and Safari in default.
Causing the CSS grid not to work properly because it pushes out the first 2 columns, therefore the third shrinks.
Without word-break:
With word-break:
> fix(dynamic-content-title): word-break and hyphens issue

- .storybook/preview.js
- components/AuthenticationBlock/package.json
- components/AuthenticationBlock/src/index.scss
- components/AuthenticationBlock/src/stories/bem.stories.mdx
- components/AuthenticationBlock/tsconfig.json
We thought no one was using the AuthenticationBlock, but as @YourivHDenHaag found out today it is actually used https://denhaag.staging.acato.nl/nl/parkeren/plattegronden-en-parkeerkosten/
> fix: add removed authentication block and mark it deprecated

- components/Accordion/src/index.scss
- components/Breadcrumb/src/index.scss
- components/Button/src/index.scss
- proprietary/Components/src/denhaag/accordion.tokens.json
- proprietary/Components/src/denhaag/breadcrumb.tokens.json
- proprietary/Components/src/denhaag/button.tokens.json
Wrong font-weight 100 in Firefox:
- Accordion panel
- Breadcrumb
- Buttons
Font-weight correction/explicit font-weight 400, caused by Firefox font-weight inheritance:
- Accordion panel
- Breadcrumb
- Buttons
- Accordion: https://www.figma.com/file/JpoY3waVoQGlLQzQXTL9nn/Design-System---Gemeente-Den-Haag?node-id=1585%3A0
- Breadcrumb: https://www.figma.com/file/JpoY3waVoQGlLQzQXTL9nn/Design-System---Gemeente-Den-Haag?node-id=1569%3A5671
- Button: https://www.figma.com/file/JpoY3waVoQGlLQzQXTL9nn/Design-System---Gemeente-Den-Haag?node-id=1%3A656
closes #1110
> style(font-weight): accordion, breadcrumb, button

- components/AnchorCollapse/src/index.scss
- proprietary/Components/src/denhaag/anchor-collapse.tokens.json
- to much margin above anchor content when collapsed
- move margin anchor content to desktop (not-collapsed)
- https://www.figma.com/file/JpoY3waVoQGlLQzQXTL9nn/Design-System---Gemeente-Den-Haag?node-id=1628%3A287
closes #1117
> style(anchor-collapse): remove margin

- .github/workflows/cicd-website.yml
For v1 of the website we have decided to split the code and responsibilities for the website components and CSS in a separate branch.
To ensure Acato can use this code in a package as they did before with the package from the npm registry we add a build step to publish the website code to the github registry instead.
I've already added a website branch just now with some editor rights, changed the access for acato-team and the design-system team and added some minor settings for the website branch to make it protected still and prevent merge commits.
Once this code is merged we will change the merge/admin rights on the main branch.
> build: add cicd for website branch

- components/Breadcrumb/README.md
- components/Breadcrumb/src/index.scss
- components/Breadcrumb/src/stories/bem.stories.mdx
- proprietary/Components/src/denhaag/breadcrumb.tokens.json
- For viewports under 1024px, just like on mobile, we show the breadcrumb with back arrow.
- For 5 items or more we use truncation (or the collapsed icon).
- Always show the 1st page in the path and the current one.
- We display the collapsed icon for each hidden page. It is also clickable and takes you to the page.
- For each hidden page, we also display a tooltip. This shows the name of the page. It did not exist and was therefore designed.
- We break off the current page, or the last item, with an ellipsis. 
- https://www.figma.com/file/JpoY3waVoQGlLQzQXTL9nn/Design-System---Gemeente-Den-Haag?node-id=1569%3A5671
- https://user-images.githubusercontent.com/95216123/194615050-0a2a54d7-4c79-4d17-99a3-3c3d6ab8d10d.mov
- https://user-images.githubusercontent.com/95216123/194615091-5dc80f17-6 …
> style(breadcrumb): change media query

- components/Button/src/index.scss
- components/Typography/src/heading.scss
- components/Typography/src/paragraph.scss
This PR reverts some changes made earlier, which broke many components. The PR can be merged after the new Den Haag website branch is ready.
We are going to write out spacing rules, and translate those rules to styling to fix the issue with spacing between all kinds of components.
> fix: remove new spacing rules, which broke many components/templates

- components/Breadcrumb/src/index.scss
1. HOTFIX for the breadcrumbs when multiple dots must be shown on desktop;
2. Re-orden CSS properties alphabetically for readability;
3. Replace `/* */` with `//` so the comment will be removed in the build.
> style(breadcrumb): set media-query and reorden alpha~

- components/AuthenticationBlock/src/stories/bem.stories.mdx
- proprietary/Components/src/denhaag/authentication-block.tokens.json
While reverting the removal of this component the design-token file and stores where ignored
With this commit the CSS, tokens and stories are back to normal
> fix: revert authentication block to last stable version

- proprietary/Components/src/denhaag/step-marker.tokens.json
Typo, used `denhaag.color.orange.5` where the connector should have the same color as the border `denhaag.color.orange.4`
> fix: step-marker-connector-warning-outline-color

- components/Conditions/src/index.scss
- components/Conditions/src/stories/bem.stories.mdx
- proprietary/Components/src/denhaag/conditions.tokens.json
Solve:
- vertical icon alignment correction (at top of list text instead of vertically in the middle)
Ticket comment:
- https://acato-nl.atlassian.net/browse/GDH-1018?focusedCommentId=115626
Screenshot before:
Screenhot after:
closes #1204
> fix(conditions): fix icon vertical alignment

- components/ProcessSteps/src/index.tsx
Both Conduction and Utrecht are using `{ ProcessSteps }`. Renaming makes it harder for them to upgrade.
Of course we only release `alpha` packages, but it is harmless to support `ProcessSteps` for a while longer anyway.
Added the export back but with a deprecation warning for now.
> fix: add deprecated ProcessSteps export

- components/Procedure/src/StepList.scss
- components/Procedure/src/index.scss
- components/Procedure/src/stories/bem.stories.mdx
- proprietary/Components/src/denhaag/procedure.tokens.json
Aanpassingen:
- afstand tussen markers verminderd
- fix voor witruimte op desktop tussen marker lijnen
- externe link zoals https://www-denhaag-nl--62d1558ac36c853a5aaad43f.chromatic.com/?path=/docs/css-navigation-link--external-link
closes #1239
> fix(procedure): change distances, fix marker lines desktop, change external link, refactor

- components/Procedure/src/StepList.scss
- components/Procedure/src/index.scss
- binnen WordPress wordt verkeerde css variabel waarde geladen voor de afstand tussen list items /markers(in storybook wel correct)
- zowel in WordPress als Storybook de correcte weergave van de afstand tussen list items/markers
- twee css variabel overwrites verhuist van file, voor correcte werking
closes #1240
> fix(procedure): move css variables refactor

- components/LinkGrid/package.json
- components/ReadSpeaker/package.json
Fix versioning for Link Grid and Readspeaker
> feat: gdh-968 | fix versioning for link grid and readspeaker

- components/Conditions/src/index.scss
- proprietary/Components/src/denhaag/conditions.tokens.json
Closes GDH-1106: feedback UX conditions component.
Using clip-path instead of :before and :after pseudo elements
> feat: gdh-1106 | feedback conditions component

- components/Image/src/index.scss
- proprietary/Components/src/denhaag/image.tokens.json
Firefox font weight fix:
`.denhaag-image__figcaption-text` hoort de font-weight van de parent element `.denhaag-image__figcaption` te erven, maar dat doet het niet in firefox.
> fix(image): firefox fontweight fix

- components/CardNews/src/index.scss
- components/CardNews/src/stories/bem.stories.mdx
Storybook update voor A11Y News Card 
Todo: Gutenberg block
> fix: gdh-1105 | news card flex-direction reverse

- components/CtaImageContent/src/index.scss
- components/CtaImageContent/src/stories/bem.stories.mdx
- proprietary/Components/src/denhaag/cta-image-content.tokens.json
Change order of image and content to ensure the readspeaker always reads the card titles and content before the image alt
> feat: gdh-1237 | A11Y - Content before image

- components/Accordion/src/AccordionToggle.js
- components/Accordion/src/index.scss
- components/Accordion/src/stories/bem.stories.mdx
- proprietary/Components/src/denhaag/accordion.tokens.json
In de huidige opzet worden accordions op basis van height getoond of niet (height: 0 is gesloten). Maar als de height 0 is, kun je nog steeds door de content heen tabben. De fix hiervoor is om de content op display: none te zetten. Om nog steeds de open / close animatie te tonen, zetten we de content eerst op display: block en daaarna de juiste height, voordat we de open animation tonen.
> fix: gdh-1221 | focus on accordion content

- components/DescriptionList/src/index.scss
- components/DescriptionList/src/stories/bem.stories.mdx
- proprietary/Components/src/denhaag/description-list.tokens.json
Fixed incorrect classname 
Closes #1296
> fix: description-list caption class

- packages/components-react/package.json
- pnpm-lock.yaml
Fixes missing file import
> Hoi! Ik probeerde in een Storybook Status te importeren uit @gemeente-denhaag/components-react en kreeg toen ik 'm probeerde te gebruiken in Storybook deze error:
ERROR in ../../node_modules/.pnpm/@gemeente-denhaag+components-react@0.1.1-alpha.267_react-dom@17.0.2_react@16.14.0/node_modules/@gemeente-denhaag/components-react/dist/mjs/index.js 1:626-662
> Module not found: Error: Can't resolve '@gemeente-denhaag/file' in '/Users/hdv/Code/nl-design-system/themes/node_modules/.pnpm/@gemeente-denhaag+components-react@0.1.1-alpha.267_react-dom@17.0.2_react@16.14.0/node_modules/@gemeente-denhaag/components-react/dist/mjs'
> Die is te verhelpen door file los te installeren, maar wel gek? Zit er op de één of andere manier een relatie tussen file en progress-steps? …
> build: fix missing file component import

- components/DescriptionList/src/DescriptionList.tsx
items of the description list had a type of "string" I changed that to "React.ReactNode" so it is easier to use in multiple situations
> fix description list type

- package.json
Removed this script to prevent confusion. Bootstrap isn't supported since Lerna v7.
> Removed lerna bootstrap script

- components/Checkbox/src/index.scss
the name was changed in Utrecht so the tokens.json file also is named "checkbox" 
Proposal to Remove "custom" and maybe even remove the Den Haag checkbox and just use the Utrecht checkbox
> Checkbox remove custom from classname

- .ncurc.major.js
- packages/storybook/package.json
- pnpm-lock.yaml
@Robbert door de Prettier upgrade in de Storybook package kwam er een bug mee die alleen zichtbaar is als je Storybook draait en een story opent. Heb Prettier voor nu even een downgrade gegeven. 
https://github.com/whitespace-se/storybook-addon-html/issues/104
> Fix Storybook Prettier

- components/Tab/src/index.tsx
- packages/storybook/src/react/Tabs.stories.tsx
Wanneer een tab child geüpdatet wordt vind er op dit moment geen rerender plaats omdat de tabData opgeslagen wordt in de state van de het tab component. Door een useEffect toe te voegen als de tabData veranderd is dit nu opgelost.
> Update tabs when data change

- .github/workflows/cicd.yml
- Use explicit version numbers everywhere
- Move `pnpm/action-setup` before `actions/setup-node` and make the latter use the pnpm cache
- Remove `actions/cache` entirely as it is no longer needed
> build: update cicd workflow

- packages/storybook/src/css/Sidenav.stories.tsx
- packages/storybook/src/react/Sidenav.stories.tsx
The docs for the sidenav were still using button docs. Set them to the correct docs for the CSS and React story
> docs: add sidenavigation docs to story

- components/Sidenav/src/index.tsx
- rollup.config.mjs
Bij het implementeren van de sidenav-component van Den Haag kwam ik een fout tegen. We gebruiken React-componenten zoals sidenav in Next.js, maar er gaat iets mis bij server-side rendering. Telkens wanneer de component wordt gebruikt, krijgen we een foutmelding door de CSS-injectiecode: `document is undefined`
Met deze kleine check `if (typeof document !== 'undefined') { ... } ` wordt de CSS-injectie overgeslagen tijdens server-side rendering, hopelijk werken alle componenten nu goed in Next.js.
> Undefined document.title CSS injection bug fix

- .github/workflows/cicd.yml
- package.json
The "packageManager" field is picked up by "pnpm/action-setup" so remove the explicit version in the workflow jobs
An environment variable `ENABLE_EXPERIMENTAL_COREPACK=1` was added to the Vercel build environment. This guarantees that Vercel will use corepack which is a workaround because at this time pnpm 9 is not officially supported yet.
> build: add "packageManager" to package.json

- .husky/commit-msg
- .husky/post-merge
- .husky/pre-commit
- package.json
- Clean up hook scripts
- Use `pnpm exec` instead of `npx` in hook scripts
- Replace package.json#postinstall with package.json#prepare
> fix: husky 9 configuration

- .github/workflows/cicd.yml
Update all GitHub Actions to their latest versions and pin versions using hashes to prevent tampering. Tags are added as comments and both tags and hashes will be updated in subsequent Dependabot pull requests
> build: update GitHub Actions

- components/ButtonLink/src/index.tsx
- components/Checkbox/src/index.tsx
- components/FormField/src/index.tsx
- components/FormFieldDescription/src/index.tsx
- components/FormFieldErrorMessage/src/index.tsx
- components/FormFieldSet/src/index.tsx
- components/FormLabel/src/index.tsx
- components/LinkButton/src/index.tsx
- components/OrderedList/src/index.tsx
- components/RadioButton/src/index.tsx
- components/StatusBadge/src/index.tsx
- components/TextInput/src/index.tsx
- components/Textarea/src/index.tsx
- components/UnorderedList/src/index.tsx
Om de volgende melding te voorkomen bij het gebruik van de package:
SyntaxError: Cannot use import statement outside a module
Module /Users/borai/Developer/nl-portal-frontend-libraries/node_modules/.pnpm/@gemeente-denhaag+status-badge@0.3.0-alpha.5_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/@gemeente-denhaag/status-badge/dist/mjs/index.js:1 seems to be an ES Module but shipped in a CommonJS package. You might want to create an issue to the package "@gemeente-denhaag/status-badge" asking them to ship the file in .mjs extension or add "type": "module" in their package.json.
> Default export

- components/Modal/src/_modal-footer.scss
- proprietary/Components/src/denhaag/modal.tokens.json
Nieuw design heeft de buttons in de model rechts uitgelijnd. 
https://www.figma.com/design/E2xRxGbRd5qboVllqkADIQ/🛖-Vakantieverhuur---MijnDenHaag?node-id=9482-11120&node-type=INSTANCE&m=dev
> Modal actions align right

- components/ProcessSteps/src/tokens.json
- packages/storybook/src/react/ProcessSteps.stories.tsx
We have had this file in the Utrecht repo for some time now, but really it belongs in this denhaag repo.
https://github.com/nl-design-system/utrecht/blob/main/components/process-steps/src/tokens.json
Once this PR is merged, we can remove it from the utrecht repo.
> docs: document process steps tokens in Storybook

- components/Alert/src/index.scss
- components/AuthenticationBlock/src/index.scss
- components/Image/src/index.scss
- components/Image/src/stories/bem.stories.mdx
- components/ProcessSteps/src/StepList.scss
- components/ProcessSteps/src/index.scss
Fix margin issues with specific blocks.
1. Headings also are prefixed with `utrecht` therefor we use that instead of `-paragraph`,
2. xl to 2xl due to message of design on Slack;
3. Apply correct margin conform design, therefor we can reduce CSS in the plugin;
closes #1620
> style(image, alert, procedure/process): fix margin styles

- components/HighlightedLinks/src/index.scss
- components/LinkGroup/src/index.scss
Rebase CSS from child to parent component, which had the exact same issue.
closes #1700 #1699 #1701
> style(link-group): rebase css from child to parent

- components/ImageBanner/src/index.scss
- components/Procedure/src/stories/bem.stories.mdx
- components/ProcessSteps/src/Step.scss
- Set marge between paragraph and image-banner, set to "Friendly" due to input of design.
- Remove offset of 10px in the steps, the 10px was causing a whitespace;
- Added a smaller preview, due to the issue only appear on smaller screens.
Cleanup closed branches:
Closes #1675 #1620 #1698 #1697
> Bugfixes www-denhaag-nl/gdhs-60

- components/AuthenticationBlock/src/index.scss
Difference in height of images causes difference in white space. Add aspect-ratio variable to the parent denhaag-image class to compensate.
> GDHS-63 Bugfix Authenticationblock eHerkenning

- components/CtaImageContent/src/index.scss
- components/DynamicContent/src/index.scss
- components/FormProgress/src/index.scss
- components/Link/src/index.scss
- components/LinkGroup/src/index.scss
text-decoration none on links with icon broke the underline for links that need it, like external links outside of link groups. Moved the text-decoration none to specifically link groups.
> GDH-1647 Make all links underlined except for link group links

- components/Breadcrumb/src/index.scss
- components/Breadcrumb/src/stories/bem.stories.mdx
- components/Container/src/stories/bem.stories.mdx
Removed links from the current page item and added inline padding to the denhaag-breadcrumb__text when it's not inside an `<a>` tag, which only happens on the current page item.
> style(breadcrumbs): remove links from current page item

- packages/storybook/src/denhaag/License.stories.tsx
Import the license from the root of the repository to display in Storybook, either as a separate page or as part of the introduction or README, to fulfil the requirement in step [EUPL-1.2 licentie toegepast](https://nldesignsystem.nl/handboek/estafettemodel/componenten/community-stappenplan/voor-organisaties/#eupl-12-licentie-toegepast) that the organisation's Storybook should have the EUPL-1.2 license available within Storybook.
closes #1810
> docs: display eupl 1.2 license in storybook (#1810)

- .changeset/empty-mice-raise.md
- packages/web-components/case-card/README.md
Include the CC0.1.0 license at the top of the component README, using `` so that anyone is allowed to freely use the component.
closes #1814
> docs: add cc0 license to case card (#1814)

- .changeset/strong-readers-eat.md
- components/SideNavigation/src/SideNavigation.tsx
The NumberBadge was hardcoded in the SideNavigation component, rendering it unusable.
Closing issues
closes #1852
> Fix: make NumberBadge universal for SideNavigation
