- src/components/IconButton/src/index.tsx
> add defaults to icon button

- README.md
Updates the usage section of the readme to display a correct import.
> Update usage section in README

- src/components/Icons/src/index.tsx
I installed a spelling checker in vscode 😅
> Fix typos in icon names

- src/styles/BaseStyles/src/globals.module.css
> Add hyphen to font-fize css variables

- src/components/IconButton/src/index.tsx
Quick addition to IconButton, I wonder how this was missed as it seems unusable without this prop.
> Added onClick prop to IconButton

- .storybook/main.js
> fix babel warning

- src/components/BaseProps/src/index.tsx
> added id property to baseprops

- .github/dependabot.yml
> too many PR's

- package.json
- yarn.lock
We're not using gh-pages. This PR removes the dependency.
> Remove gh-pages dependency

- package.json
- yarn.lock
Remove the dependency on an unused package: yarn-outdated-formatter
closes #260
> Remove yarn-outdated-formatter dependency

- .github/pull_request_template.md
> turn PR notice into comment

- src/components/Button/src/index.tsx
- src/components/Menu/src/Menu.stories.tsx
> Add touch event to onclick

- src/components/IconButton/package.json
- src/components/IconButton/src/index.tsx
- src/components/IconButton/src/mui-override.css
- src/components/List/src/ListItem.tsx
This issue disables some animation and hover which is provided by MUI by default.
We should remove this in the component because otherwise we have to remove these in each component that uses IconButton.
> removed animations and hover color for IconButton

- src/components/List/src/List.tsx
- src/meta-packages/datadisplay/package.json
During testing of the components in a new react project the following warnings occured:
```
warning @gemeente-denhaag/denhaag-component-library > @gemeente-denhaag/datadisplay > @gemeente-denhaag/listitemtext@0.1.7: use @gemeente-denhaag/list instead
warning @gemeente-denhaag/denhaag-component-library > @gemeente-denhaag/datadisplay > @gemeente-denhaag/listitemsecondaryaction@0.1.7: use @gemeente-denhaag/list instead
warning @gemeente-denhaag/denhaag-component-library > @gemeente-denhaag/datadisplay > @gemeente-denhaag/listitemavatar@0.1.7: use @gemeente-denhaag/list instead
warning @gemeente-denhaag/denhaag-component-library > @gemeente-denhaag/datadisplay > @gemeente-denhaag/listsubheader@0.1.7: use @gemeente-denhaag/list instead
warning @gemeente-denhaag/denhaag-component-library > …
```
> removed duplicate dependencies

- src/components/Button/src/mui-override.css
> Fix Mui active styling on button causing shadow

- .github/workflows/cicd.yml
- .husky/commit-msg
- commitlint.config.js
- package.json
- yarn.lock
This PR enforces the use of conventional commits by adding a husky hook for commit-lint, as well as automating prerelease version publishing.
TODO:
closes #43 #44
> Automated versioning and release

- src/components/Tab/src/Tab.tsx
- src/components/Tab/src/TabPanel.tsx
- src/components/Tab/src/Tabs.tsx
- src/components/Tab/src/styles/mui-override.css
- src/components/Tab/src/styles/tab-panel.css
- src/components/Tab/src/styles/tab.css
- src/components/Tab/src/styles/tabs.css
- src/styles/Components/src/denhaag/tab/style-dictionary.json
Work in progress
**TODO**
closes #379
> Tab component design impl

- src/components/Card/src/Card/Card.tsx
- src/components/Card/src/Card/card.css
- src/styles/Components/src/denhaag/card/element-modifier.style-dictionary.json
- src/styles/Components/src/denhaag/card/element.style-dictionary.json
- src/styles/Components/src/denhaag/card/modifier.style-dictionary.json
This component fixes the accessibility contrast issues with the card, as well as adding the new inactive (gray) variant
> Card: add new colors and inactive state

- src/components/Accordion/README.md
- src/components/AnchorNavigation/README.md
- src/components/BadgeStatus/README.md
- src/components/Breadcrumb/README.md
- src/components/CardCase/README.md
- src/components/CardGuide/README.md
- src/components/CardProduct/README.md
- src/components/CardSubject/README.md
- src/components/CardTheme/README.md
- src/components/Chat/README.md
- src/components/Datepicker/README.md
- src/components/Divider/README.md
- src/components/Drawer/README.md
- src/components/FileDownload/README.md
- src/components/FormNavigation/README.md
- src/components/List/README.md
- src/components/Modal/README.md
- src/components/Pagination/README.md
- src/components/Radio/README.md
- src/components/Select/README.md
- src/components/Subnavigation/README.md
- src/components/Switch/README.md
- src/components/Tab/README.md
- src/components/Table/README.md
- src/components/TextField/README.md
- src/components/Timeline/README.md
Addition of UX documentation that was previously housed in Figma to be made available to UX designer from outside of the municipality of Den Haag.
https://github.com/nl-design-system/denhaag/issues/429
> Add additional component UX documentation

- .storybook/stories/Introduction.stories.mdx
> docs: add getting started documentation

- .github/ISSUE_TEMPLATE/feature_request.md
- .github/dependabot.yml
- .github/workflows/cicd.yml
- CONTRIBUTING.md
- README.md
- components/Alert/README.md
- components/BadgeCounter/README.md
- components/Button/README.md
- components/Checkbox/README.md
- components/DotIndicator/README.md
- components/FormControlLabel/README.md
- components/FormGroup/README.md
- components/Link/README.md
- components/Menu/README.md
- lerna.json
Aligns with all other repo's in nl-design-system organisation and helps my muscle memory
> refactor: configure `main` as default branch

- .github/dependabot.yml
> ci: use Dependabot for updating GitHub Actions too

- components/Tab/package.json
> fix: add missing dependency

- components/Button/src/stories/button.bem.stories.mdx
Remove linting from preview in storybook
> fix(button): fix button preview, removing linting exclude message

- components/PosttypeLabel/README.md
- components/PosttypeLabel/package.json
- components/PosttypeLabel/src/index.css
- components/PosttypeLabel/src/stories/posttypeLabel.bem.stories.mdx
- components/PosttypeLabel/tsconfig.json
- packages/components-css/src/index.tsx
- proprietary/Components/src/denhaag/posttypelabel.tokens.json
https://github.com/nl-design-system/denhaag/issues/629
- Label of the page type.
- styling
closes  #629
> feat(posttypelabel): add story, css, tokens

- components/EventDate/README.md
- components/EventDate/package.json
- components/EventDate/src/index.css
- components/EventDate/src/stories/eventDate.bem.stories.mdx
- components/EventDate/tsconfig.json
- packages/components-css/src/index.tsx
- proprietary/Components/src/denhaag/eventdate.tokens.json
Solve:
https://github.com/nl-design-system/denhaag/issues/655
Purpose:
- styling of event date
- style based of posttype label
closes #655
> feat(event-date): add new event date bem, css (based on posttype label)

- components/PageButtons/src/stories/bem.stories.mdx
Resolve:
correct storybook directory for Page Buttons component: from 'CSS Components' to 'CSS'
> refactor: change Meta title dir name

- components/DescriptionList/README.md
- components/DescriptionList/package.json
- components/DescriptionList/src/index.css
- components/DescriptionList/src/stories/bem.stories.mdx
- components/DescriptionList/tsconfig.json
- packages/components-css/src/index.tsx
- proprietary/Components/src/denhaag/description-list.tokens.json
- proprietary/Proprietary/src/typography.tokens.json
Solve:
https://github.com/nl-design-system/denhaag/pull/698
Purpose:
- re-add component descriptionlist
- solve merge conflict with the main branch
closes #638
> feat(descriptionlist): add comp + solve merge conflict main branch

- .stylelintrc.json
- components/Alert/src/index.scss
- components/BadgeCounter/src/index.scss
- components/Breadcrumb/src/index.scss
- components/Button/src/index.scss
- components/Card/src/CardContent/mui-override.scss
- components/Checkbox/src/index.scss
- components/CtaDownload/src/index.scss
- components/CtaEvent/src/index.scss
- components/CtaLink/src/index.scss
- components/Datepicker/src/index.scss
- components/FormControlLabel/src/index.scss
- components/FormGroup/src/index.scss
- components/IconButton/src/index.scss
- components/Icons/src/index.scss
- components/List/src/list-item-secondary-action.scss
- components/Modal/src/index.scss
- components/Note/src/index.scss
- components/PageButtons/src/index.scss
- components/Pagination/src/index.scss
- components/Tab/src/styles/tab.scss
- components/Timeline/src/styles/mui-override.scss
- components/Timeline/src/styles/step-icon.scss
- package.json
- yarn.lock
Stylelint was throwing error on usage of `@extend`. Added scss config to stylelint.
Copied new config rules from [utrecht config](https://github.com/nl-design-system/utrecht/blob/main/.stylelintrc.json)
> build: stylelint scss config

- packages/components-css/src/index.tsx
> fix: export table to component-css package

- components/UnorderedList/README.md
- components/UnorderedList/package.json
- components/UnorderedList/src/index.scss
- components/UnorderedList/src/stories/bem.stories.mdx
- components/UnorderedList/tsconfig.json
- packages/components-css/src/index.tsx
- proprietary/Components/src/denhaag/unordered-list.tokens.json
Solve:
https://github.com/nl-design-system/denhaag/issues/754
Purpose:
- html + css for unordered list
- including tokens
closes feature/#754-unordered-list
> feat(unordered-list): add unordered list html, css, tokens

- components/CtaImageContent/src/index.scss
- components/CtaImageContent/src/stories/bem.stories.mdx
- proprietary/Components/src/denhaag/cta-image-content.tokens.json
`closes #765 `
Added small variant to CtaImageContent component.
> feat: added small variant to cta-image-content component

- components/OrderedList/README.md
- components/OrderedList/package.json
- components/OrderedList/src/index.scss
- components/OrderedList/src/stories/bem.stories.mdx
- components/OrderedList/tsconfig.json
- packages/components-css/src/index.tsx
Solve:
https://github.com/nl-design-system/denhaag/issues/754
Purpose:
- html + css for ordered list
closes feature/#754-ordered-list
> feat(ordered-list): add ordered list html, css

- components/Blockquote/src/index.scss
Solve:
https://github.com/nl-design-system/denhaag/issues/779
Purpose:
- add style corrections
closes #779
> style(blockquote): add style corrections

- components/CtaImageContent/src/index.scss
- components/CtaImageContent/src/stories/bem.stories.mdx
- proprietary/Components/src/denhaag/cta-image-content.tokens.json
`closes #769 `
Added filled variant to CtaImageContent component:
https://www.figma.com/file/JpoY3waVoQGlLQzQXTL9nn/Design-System---Gemeente-Den-Haag?node-id=8141%3A24498
> feat: added filled variant to CtaImageContent component

- components/CtaDownload/src/index.scss
Solve:
https://github.com/nl-design-system/denhaag/issues/780
Purpose:
- add style corrections
closes #780
> style(cta-download): add style corrections

- components/Accordion/src/index.scss
Solve:
https://github.com/nl-design-system/denhaag/issues/778
Purpose:
- add style corrections
closes #778
> style(accordion): add styling corrections

- components/UnorderedList/src/index.scss
- components/UnorderedList/src/stories/bem.stories.mdx
Solve: https://github.com/nl-design-system/denhaag/issues/798
Purpose:
- add anchor link styling within list item
closes #798
> style(unordered-list): add styling anchor in list item

- components/Table/src/index.scss
- proprietary/Components/src/denhaag/table.tokens.json
width and max-width on table
`closes #799 `
> feat: width and max-width for table component

- components/Note/src/index.scss
- proprietary/Components/src/denhaag/note.tokens.json
Solve:
- correct right margin for external link within a Note component
Purpose: 
- reduce right margin of external link within a Note component
closes #805
> style(note): add style correction

- components/AnchorNavigation/package.json
- components/AnchorNavigation/src/index.scss
- components/AnchorNavigation/src/stories/bem.stories.mdx
- components/AnchorNavigation/tsconfig.json
- packages/components-css/src/index.tsx
- proprietary/Components/src/denhaag/anchor-navigation.tokens.json
Solve: https://github.com/nl-design-system/denhaag/issues/816
Purpose:
- add html, css, tokens
closes #818
> feat(anchor-navigation): add html, css, tokens

- components/Note/src/stories/bem.stories.mdx
Solve: https://github.com/nl-design-system/denhaag/issues/824
Purpose:
- fixing style positioning issue when adding anchor tag to text:
closes #825
> fix(note): add text div, fixing style when adding anchor tag

- components/Card/src/Card/Card.tsx
- components/Card/src/Card/card.scss
- components/Card/src/stories/react.stories.tsx
> Date is optional

- components/LinkGroup/package.json
- components/LinkGroup/src/index.scss
- components/LinkGroup/src/stories/bem.stories.mdx
- proprietary/Components/src/denhaag/link-group.tokens.json
Solve: https://github.com/nl-design-system/denhaag/issues/837
Purpose:
- correct versioning package.json
- refactoring bem, css, tokens to link component inheritance
closes #846
> style(link-group): refactor style to link inheritance

- components/LinkGroup/src/index.scss
- proprietary/Components/src/denhaag/link-group.tokens.json
Solve: https://github.com/nl-design-system/denhaag/issues/837
Purpose: add necessary styling
closes  #856
> style(link-group): add necessary styling + tokens

- components/CardNews/README.md
- components/CardNews/package.json
- components/CardNews/src/index.scss
- components/CardNews/src/stories/bem.stories.mdx
- components/CardNews/tsconfig.json
- packages/components-css/src/index.tsx
- proprietary/Components/src/denhaag/card-news.tokens.json
Solve:  https://github.com/nl-design-system/denhaag/issues/861
Purpose:
- add bem, css, tokens
closes  #862
> feat(news-card): add bem, css, tokens

- components/AnchorNavigation/src/index.scss
- proprietary/Components/src/denhaag/anchor-navigation.tokens.json
Some minor style tweaks which was feedback.
> style(anchor-navigation-button): tweak styles of the element

- components/LinkGroup/src/index.scss
- proprietary/Components/src/denhaag/link-group.tokens.json
Solve: https://github.com/nl-design-system/denhaag/issues/837
Purpose:
- add style correction for arrow
- add style correction for link focus on dark variant link group
closes #870
> style(link-group): add style corrections

- proprietary/Components/src/denhaag/anchor-collapse.tokens.json
Minor feedback point, regular to bold.
Closing old GDH branches: 
closes #845 #841 #842
> style(anchor-collapse): set summary bold instead of normal

- components/Hero/src/index.scss
- components/Hero/src/stories/bem.stories.mdx
- proprietary/Components/src/denhaag/hero.tokens.json
Solve: https://github.com/nl-design-system/denhaag/issues/876
Purpose:
- Add new variant, theme page
closes #878
> feat(hero-theme-page): add hero variant, theme page

- components/OrderedList/src/stories/bem.stories.mdx
- components/Typography/src/heading.scss
- components/Typography/src/paragraph.scss
- components/Typography/src/stories/heading1.bem.stories.mdx
- components/Typography/src/stories/heading2.bem.stories.mdx
- components/Typography/src/stories/heading3.bem.stories.mdx
- components/Typography/src/stories/heading4.bem.stories.mdx
- components/Typography/src/stories/heading5.bem.stories.mdx
- components/Typography/src/stories/paragraph.bem.stories.mdx
- components/UnorderedList/src/index.scss
- components/UnorderedList/src/stories/bem.stories.mdx
- proprietary/Components/src/denhaag/unordered-list.tokens.json
- proprietary/Components/src/utrecht/heading-1.tokens.json
- proprietary/Components/src/utrecht/heading-2.tokens.json
- proprietary/Components/src/utrecht/heading-3.tokens.json
- proprietary/Components/src/utrecht/heading-4.tokens.json
- proprietary/Components/src/utrecht/heading-5.tokens.json
- proprietary/Components/src/utrecht/heading.tokens.json
- proprietary/Components/src/utrecht/paragraph.tokens.json
Added styling for the typography for following up elements since it took the default browser margins.
> style(typography): added typography margin styles

- components/AnchorNavigation/src/index.scss
- proprietary/Components/src/denhaag/anchor-collapse.tokens.json
- proprietary/Components/src/denhaag/anchor-navigation.tokens.json
> style(anchors): apply feedback from design

- packages/components-css/src/index.tsx
> style(hero): set hero styles to the export

- components/Hero/src/index.scss
- proprietary/Components/src/denhaag/hero.tokens.json
Solve: https://github.com/nl-design-system/denhaag/issues/876
Purpose:
- additional styling for consistant responsive scaling of bottom white content block with it's parent
https://user-images.githubusercontent.com/95216123/163206968-c46617af-75c8-485e-915b-fefb35a9f293.mov
closes #895
> style(hero-theme-page): additional styling

- components/HighlightedLinks/README.md
- components/HighlightedLinks/package.json
- components/HighlightedLinks/src/index.scss
- components/HighlightedLinks/src/stories/bem.stories.mdx
- components/HighlightedLinks/tsconfig.json
- packages/components-css/src/index.scss
- proprietary/Components/src/denhaag/highlighted-links.tokens.json
Solve: https://github.com/nl-design-system/denhaag/issues/903
Purpose:
- Highlighted links are important links at the top of your page.
- add bem, css, tokens for highlighted links
closes #906
> feat(highlighted-links): add bem, css, tokens

- proprietary/Components/src/denhaag/button.tokens.json
Solve: The height of the button should be 48 px instead of 57.
Purpose:
- add style correction button large
closes #910
> style(button): add styling correction

- components/CtaDownload/src/index.scss
- components/CtaEvent/src/index.scss
- components/CtaLink/src/index.scss
- proprietary/Components/src/denhaag/cta-download.tokens.json
- proprietary/Components/src/denhaag/cta-event.tokens.json
- proprietary/Components/src/denhaag/cta-link.tokens.json
Applied new style on the cta-link, cta-download and cta-event.
> style(cta): apply new style

- components/PublicationDate/src/index.scss
> fix(puplish-date): fix random line

- components/Hero/src/index.scss
- proprietary/Components/src/denhaag/hero.tokens.json
Rebasing padding reset to larger screensize and set fallback for default container padding.
> fix(hero): rebase padding reset

- components/HighlightedLinks/src/index.scss
Solve: https://acato-nl.atlassian.net/browse/GDH-248
Purpose:
- remove margin bottom
closes #932
> style(highlighted-links): add style correction

- components/LinkGroup/src/index.scss
- proprietary/Components/src/denhaag/link-group.tokens.json
Solve: https://acato-nl.atlassian.net/browse/GDH-393
Purpose:
- change link focus border color for accesibility
closes #934
> style(link-group): change link focus border color

- components/ProcessSteps/package.json
> fix: correct export path for ProcessSteps css

- components/Button/src/index.scss
- components/Button/src/stories/bem.stories.mdx
- components/Link/src/index.scss
- components/Link/src/stories/bem.stories.mdx
Added 2 accessibility points:
1. Buttons and links to specific cursors (advised by Fernand);
2. Add screen-reader inner-element support.
> feat(link-button): accessibility sr-only to button and link

- components/ProcessSteps/src/Step.scss
- components/ProcessSteps/src/StepHeading.scss
- components/ProcessSteps/src/StepList.scss
- components/ProcessSteps/src/StepMarker.scss
- components/ProcessSteps/src/SubStep.scss
- components/ProcessSteps/src/SubStepList.scss
- components/ProcessSteps/src/SubStepMarker.scss
- components/ProcessSteps/src/SubStepMarker.tsx
- components/ProcessSteps/src/index.tsx
- proprietary/Components/src/denhaag/process-steps.tokens.json
To make Process Steps work for the design of Gemeente Utrecht we needed some tweaks to the design tokens. This PR is not fully done yet, but considering the remarks in PR #916 about the necessity of further refactorings, I though I better share my work in progress early on.
> feat: more design tokens for Process Steps component

- components/Accordion/src/index.scss
style correction accordion heading
> style(accordion): style correction accordion heading

- components/Accordion/src/index.scss
> fix(accordion): add safari specific css, remove marker

- components/UnorderedList/src/index.scss
Solve: https://acato-nl.atlassian.net/browse/GDH-500
Purpose:
- add style correction for ul link padding
closes #951
> style: add style correction link padding ul

- components/Accordion/src/AccordionToggle.js
- components/Accordion/src/index.scss
- components/Accordion/src/stories/bem.stories.mdx
- components/Accordion/src/story.js
- proprietary/Components/src/denhaag/accordion.tokens.json
Solve: https://acato-nl.atlassian.net/browse/GDH-445
Purpose:
- make accordion screen reader accessible
closes #954
> refactor(accordion): refactor for screen readers accessibility

- components/Accordion/src/index.scss
- components/Accordion/src/stories/bem.stories.mdx
- proprietary/Components/src/denhaag/accordion.tokens.json
@robbieatacato maybe we can improve this even further by adding the `aria-controls` attribute? 
See this [WAI-ARIA example](https://www.w3.org/TR/wai-aria-practices-1.2/examples/accordion/accordion.html) (source code further down the page)
_Originally posted by @bddjong in https://github.com/nl-design-system/denhaag/issues/954#issuecomment-1124640396_
closes #959
> refactor(accordion): additional accessibility attributes, some styling

- components/CtaImageContent/src/index.scss
- components/CtaImageContent/src/index.tsx
- components/CtaImageContent/src/stories/bem.stories.mdx
- proprietary/Components/src/denhaag/cta-image-content.tokens.json
Solve: https://acato-nl.atlassian.net/browse/GDH-454
Purpose:
- add accessibility for screen readers
- change clickable area with pseudo css fix
- more semantic html
closes #976
> fix(cta-image-content-accessible): make accessible for screen readers

- components/Link/src/index.scss
- components/Link/src/stories/bem.stories.mdx
- components/LinkGroup/src/index.scss
- proprietary/Components/src/denhaag/link.tokens.json
- Fixed link-icon size issue;
- Fixed icon-alignment for long links;
- Minor reducement for the CSS variable overwrite;
> fix(link-icons): fix styling in link-icon and reduce duplication

- components/Hero/src/index.scss
- proprietary/Components/src/denhaag/hero.tokens.json
Solve: https://acato-nl.atlassian.net/browse/GDH-82
Purpose:
- add content padding for hero theme page: mobile + tablet
closes #982
> style(hero-theme-page-extended): add padding for mobile + tablet

- .github/workflows/cicd.yml
This PR disabled the Cypress snapshot testing
> ci: disable snapshot testing

- .storybook/stories/Colors.stories.mdx
> docs: fix the color design tokens storybook

- components/Button/src/index.scss
- proprietary/Components/src/denhaag/button.tokens.json
- incorrect button sizes medium + large
- figma: https://www.figma.com/file/JpoY3waVoQGlLQzQXTL9nn/Design-System---Gemeente-Den-Haag?node-id=1%3A656
- check current styles button
- correct button sizes
#closes
> style(button): medium + large size corrections

- proprietary/Components/src/openforms/button.tokens.json
by closing button-token properly
> fix: storybook build

- components/AnchorCollapse/src/index.scss
- proprietary/Components/src/denhaag/anchor-collapse.tokens.json
- incorrect spacings
Purpose:
- apply correct spacing styles
closes #1070
> style(anchor collapse): style corrections

- components/DynamicContent/src/index.scss
- arrow position not up-to-date
- arrow visibility mobile not up-to-date
- update arrow position
- update arrow visibility on mobile
Figma: https://www.figma.com/file/JpoY3waVoQGlLQzQXTL9nn/Design-System---Gemeente-Den-Haag?node-id=17909%3A107831
closes #1087
> style(dynamic-content-card): change arrow position + visibiliy

- components/Table/src/index.scss
- proprietary/Components/src/denhaag/table.tokens.json
- to narrow table cells and headings for content
- set a minimum width for table cells and headings
closes #1095
> style(table): add min width table cells + heading

- components/FloatingContact/package.json
Update Floating Contact package version.
closes #1097
> build(package version): floating contact

- components/FloatingContact/README.md
Change readme colors.
closes  #1098
> docs(floating-contact): change readme colors

- components/Table/src/TableScroll.js
- components/Table/src/index.scss
- components/Table/src/stories/bem.stories.mdx
- proprietary/Components/src/denhaag/table.tokens.json
- missing responsive shadows
- add responsive shadows as in figma: https://www.figma.com/file/JpoY3waVoQGlLQzQXTL9nn/Design-System---Gemeente-Den-Haag?node-id=5213%3A16235
closes #1101
> feat(table): add responsive container shadows

- components/LinkGroup/src/index.scss
- components/UnorderedList/src/index.scss
- proprietary/Components/src/denhaag/link-group.tokens.json
- proprietary/Components/src/denhaag/unordered-list.tokens.json
Solve:
missing explicit font-weight declarations of
- ul
- ol
- link-group
Solve:
- correct font-weights for above components
closes #1102
> style(font-weight): font-weight of ul, ol, link-group

- components/CtaImageContent/src/index.scss
- proprietary/Components/src/denhaag/cta-image-content.tokens.json
- border-radius depricated
- cta image content variant --filled white border
- remove border-radius
- remove white border --filled variant
- https://www.figma.com/file/JpoY3waVoQGlLQzQXTL9nn/Design-System---Gemeente-Den-Haag?node-id=8141%3A24498
closes #1106
> style(cta-image-content): some style corrections

- components/Blockquote/src/index.scss
- proprietary/Components/src/denhaag/blockquote.tokens.json
- author text is uppercase
- remove uppercase on author text
- https://www.figma.com/file/JpoY3waVoQGlLQzQXTL9nn/Design-System---Gemeente-Den-Haag?node-id=8123%3A22417
closes #1107
> style(blockquote): change author text to lowercase

- components/Blockquote/src/index.scss
- proprietary/Components/src/denhaag/blockquote.tokens.json
- author/attribution text letter-spacing outdated
- remove letter-spacing author/attribution text
- https://www.figma.com/file/JpoY3waVoQGlLQzQXTL9nn/Design-System---Gemeente-Den-Haag?node-id=8123%3A22417
closes #1108
> style(blockquote): remove letter-spacing

- components/Table/src/TableScroll.js
- components/Table/src/index.scss
- proprietary/Components/src/denhaag/table.tokens.json
- disabling buttons on window resize
- disabling shadows on window resize
- shadows blocked horizontal touch scrolling
- shadows blocked horizontal mouse scrolling
- fix all the above
- https://www.figma.com/file/JpoY3waVoQGlLQzQXTL9nn/Design-System---Gemeente-Den-Haag?node-id=5213%3A16235
closes #1109
> fix(table): fix btns + shadows, window resize

- components/Typography/src/heading.scss
- margin above headings headings 1, 2, 3, 4, 5 when following other components
- apply repsonsive margins above headings 1, 2, 3, 4, 5 when following other components
- https://www.figma.com/file/fCCe3DA2gCfsqYOm0vuPsi/Final-UI---Transitie-Online?node-id=7445%3A94085
closes  #1111
> style(heading): responsive margins

- packages/keycloak/LICENSE.md
- packages/keycloak/package.json
- packages/keycloak/rollup.config.js
- packages/keycloak/src/_fonts.scss
- packages/keycloak/src/index.scss
Add keycloak package with all CSS needed for Keycloak
> feat: added keycloak package

- components/Checkbox/src/index.scss
- proprietary/Components/src/denhaag/checkbox.tokens.json
Purpose:
- add checkbox animation: tokens + css
Figma:
- https://www.figma.com/proto/qr18lJ6PZP8HMAN77HBxCp/Schetsboek---Transitie-Online?page-id=686%3A234006&node-id=1461%3A305763&viewport=1195%2C1143%2C0.12&scaling=min-zoom&starting-point-node-id=1385%3A301248&show-proto-sidebar=1&hide-ui=1
Screen capture:
https://user-images.githubusercontent.com/95216123/204328248-7b5abc4c-8442-4374-96dc-dc63504fbf29.mov
#closes #1152
> style(checkbox): add animation

- proprietary/Components/src/denhaag/card-news.tokens.json
- proprietary/Components/src/denhaag/checkbox.tokens.json
Purpose:
- fixing build error not finding token
#closes #1153
> build(checkbox-animation): refactor token value

- proprietary/Components/src/denhaag/accordion.tokens.json
- proprietary/Components/src/denhaag/anchor-collapse.tokens.json
Purpose:
- change transition duration (slower) acoordion
- change transition duration (slower) anchor collapse
> fix(accordion-anchor): change transition durations

- components/Breadcrumb/src/index.scss
- proprietary/Components/src/denhaag/breadcrumb.tokens.json
-animate breadcrumb tooltip on hover
- https://www.figma.com/proto/qr18lJ6PZP8HMAN77HBxCp/Schetsboek---Transitie-Online?page-id=686%3A234006&node-id=1461%3A305689&viewport=1195%2C1143%2C0.12&scaling=min-zoom&starting-point-node-id=1385%3A301248&show-proto-sidebar=1&hide-ui=1
https://user-images.githubusercontent.com/95216123/212723219-dbfd6bbc-7b47-444c-9c13-3d2ec6a50758.mov
> style(breadcrumb tooltip): refactor + add animation

- components/CardNews/src/index.scss
- components/CardNews/src/stories/bem.stories.mdx
- proprietary/Components/src/denhaag/card-news.tokens.json
- update current news card with additional date
https://www.figma.com/file/JpoY3waVoQGlLQzQXTL9nn/Den-Haag-Design-System?node-id=11536%3A65392&t=T0OVOyyLqwbTs0DT-1
closes #1197
> style(news card): updated version with date

- components/Hero/src/index.scss
- components/Hero/src/stories/bem.stories.mdx
- proprietary/Components/src/denhaag/hero.tokens.json
- html
- css
- tokens
https://www.figma.com/file/JpoY3waVoQGlLQzQXTL9nn/Den-Haag-Design-System?node-id=24917%3A125160&t=cwcxhhuglxevXWWl-1
closes #1202
> feat(hero theme image): add hero theme image variant

- components/Alert/src/index.scss
Solve:
- add missing heading margin css
Ticket comment:
- https://acato-nl.atlassian.net/browse/GDH-1005?focusedCommentId=115456
closes #1203
> fix(alert): add missing heading margin css

- components/Alert/src/index.scss
- proprietary/Components/src/denhaag/alert.tokens.json
Doel:
- styling correcties: https://acato-nl.atlassian.net/browse/GDH-1005?focusedCommentId=116016
closes #1207
> fix(alert): styling corrections

- components/Alert/src/index.scss
- components/Conditions/src/stories/bem.stories.mdx
- proprietary/Components/src/denhaag/alert.tokens.json
- proprietary/Components/src/denhaag/conditions.tokens.json
Style correcties:
- alert css
- conditions css, tokens, html
closes #1213
> fix(alert and conditions): style corrections

- components/Hero/src/index.scss
- proprietary/Components/src/denhaag/hero.tokens.json
Doel:
- styling correcties/fix/update
Figma:
- https://www.figma.com/file/JpoY3waVoQGlLQzQXTL9nn/Den-Haag-Design-System?node-id=24917%3A125160&t=cwcxhhuglxevXWWl-1
Ticket feedback:
- https://acato-nl.atlassian.net/browse/GDH-1017?focusedCommentId=116600
Screenshots:
closes #1215
> fix(hero theme image): add corrections, tokens, css

- components/Procedure/src/index.scss
- components/Procedure/src/stories/bem.stories.mdx
- proprietary/Components/src/denhaag/procedure.tokens.json
- toevoegen van externe link styling
- toevoegen van responsive styling
- refactor
https://www.figma.com/file/JpoY3waVoQGlLQzQXTL9nn/Den-Haag-Design-System?node-id=25264%3A131066&t=PsWFBfBt5PKhbJEo-4
closes #1234
> fix(procedure): additional link styling + refactor

- packages/components-css/src/index.scss
Add missing package to index 
closes
> build(image banner): add image banner package to index

- components/Procedure/package.json
fix package version:
dezelfde als de rest van de componenten
> build(procedure): fix package version

- components/LinkGrid/src/index.scss
Fixes hover state for GDH-1093 Link grid
> feat: gdh-1093 | Link grid hover state

- components/Procedure/src/index.scss
- components/Procedure/src/stories/bem.stories.mdx
- proprietary/Components/src/denhaag/procedure.tokens.json
Heading toevoegen:
- html
- css
- tokens
closes #1247
> fix(procedure title): add heading html, css, tokens

- packages/components-css/src/index.scss
Added Readspeaker styles to components index
> build: gdh-968 | readspeaker

- components/ReadSpeaker/src/index.js
- components/ReadSpeaker/src/index.scss
- proprietary/Components/src/denhaag/readspeaker.tokens.json
Completes Readspeaker UX Feedback
> feat: gdh-968 | readspeaker PR feedback

- components/LinkGrid/src/index.scss
Closes GDH-1106 - UX feedback on first child border
> feat: gdh-1093 | link grid border bottom fix first child

- components/Conditions/src/index.scss
- proprietary/Components/src/denhaag/conditions.tokens.json
> feat: gdh-1106 | UX feedback after PR

- components/FloatingContact/src/index.scss
- proprietary/Components/src/denhaag/floating-contact.tokens.json
> fix: gdh-1226 | Floating contact titles contrast

- components/Image/src/index.scss
- proprietary/Components/src/denhaag/image.tokens.json
> fix(image figcaption): font-weight correction

- components/OrderedList/src/stories/bem.stories.mdx
- components/UnorderedList/src/index.scss
- components/UnorderedList/src/stories/bem.stories.mdx
- proprietary/Components/src/denhaag/unordered-list.tokens.json
Fix voor zowel unordered lists als ordered lists met externe links.
closes #1263
> fix(unordered ordered lists): fix for external links

- components/Card/src/index.tsx
Export all React card components
> fix: fix exports for react card components

- components/Card/src/Card/CaseCard.tsx
- components/Card/src/Card/SubjectCard.tsx
Added the action/link to the smart components
> added link/action to refactored casecard and subjectcard

- components/InlineCarousel/src/index.scss
- components/InlineCarousel/src/stories/bem.stories.mdx
- proprietary/Components/src/denhaag/inline-carousel.tokens.json
> feat: gdh-1258 | UX Feedback

- .stylelintrc.json
- components/FloatingContact/src/index.scss
- components/FloatingContact/src/storybook.scss
- proprietary/Components/src/denhaag/floating-contact.tokens.json
- Reduced CSS;
- Allowed `-inline`  `-block`;
- CSS tweaks
> style(floating-contact): add style tweak for weird screen-sizes

- components/InlineCarousel/src/index.scss
- proprietary/Components/src/denhaag/inline-carousel.tokens.json
> fix: gdh-1272 | UX border feedback

- components/FloatingContact/src/FloatingContact.js
Calculate element height to add zoom class
> feat: gdh-1214 | floating height calc

- components/FullwidthSlider/src/index.scss
- components/LinkGrid/src/index.scss
Doel:
- verwijderen fullbleed widths
- er komt een fullwidth template namelijk
closes #1311
> fix(fullbleed widths): widths corrections

- components/CtaImageContent/src/index.scss
Doel:
- css focus correctie
closes #1314
> refactor(cta image content): change focus css

- .prettierignore
- .storybook/stories/Introduction.stories.mdx
- .storybook/stories/templates/CaseDetail-page.stories.mdx
- .storybook/stories/templates/Login-page.stories.mdx
- .storybook/stories/templates/Overview-page.stories.mdx
- components/Action/src/stories/bem.stories.mdx
- components/Action/src/stories/react.stories.mdx
- components/Checkbox/src/index.tsx
- components/Datepicker/src/index.tsx
- components/ProcessSteps/src/SubStepHeading.tsx
- components/Radio/src/index.tsx
- components/Sheet/src/use-escapekey.tsx
- tsconfig.build.json
> chore: various small fixes to prepare for major updates

- components/Avatar/package.json
- components/Avatar/src/Avatar.tsx
- components/Avatar/src/index.scss
- components/Avatar/src/index.tsx
- components/Avatar/tsconfig.json
- pnpm-lock.yaml
Add stylesheet with current avatar styles and fallbacks and remove material dependency
> refactor: remove material-ui dependency from avatar

- components/ContactTimeline/README.md
- components/ContactTimeline/package.json
- components/ContactTimeline/src/index.scss
- components/ContactTimeline/src/index.tsx
- components/ContactTimeline/src/stories/bem.stories.mdx
- components/ContactTimeline/src/stories/react.stories.mdx
- components/ContactTimeline/tsconfig.json
- components/ProcessSteps/src/Step.tsx
- components/ProcessSteps/src/_StepHeader.scss
- components/ProcessSteps/src/index.tsx
- components/StepMarker/src/StepMarker.tsx
- components/StepMarker/src/StepMarkerConnector.tsx
- components/StepMarker/src/_StepMarker.scss
- components/StepMarker/src/_StepMarkerConnector.scss
- pnpm-lock.yaml
- proprietary/Components/src/denhaag/contact-timeline.tokens.json
- proprietary/Components/src/denhaag/process-steps.tokens.json
- proprietary/Components/src/denhaag/step-marker.tokens.json
Work in progress, but due to time pressure (hackathon) a release of this experimental/WIP component.
> WIP contact timeline mobile

- components/ContactTimeline/src/stories/bem.stories.mdx
> fix: resolve prettier error

- components/Action/src/index.tsx
Forgot to import the css file...
> fix: action component css

- CONTRIBUTING.md
- components/Divider/package.json
- components/Divider/src/index.scss
- components/Divider/src/index.tsx
- components/FormGroup/package.json
- components/StylesProvider/package.json
- components/StylesProvider/src/index.tsx
- package.json
- pnpm-lock.yaml
- proprietary/Components/src/denhaag/divider.tokens.json
- rollup.config.mjs
- Refactored Divider component
- Removed MUI style provider
- Removed MUI package from components
- Removed MUI package from root
- Removed MUI config from Rollup
- Removed MUI reference from docs
> feat: removed Material UI

- proprietary/Components/src/denhaag/radio.tokens.json
- proprietary/Components/src/utrecht/checkbox.tokens.json
> fix: :bug: fixed faulty tokens

- proprietary/Components/src/utrecht/radio-button.tokens.json
> feat: :sparkles: added radio button tokens and filled them

- components/Page/src/index.scss
- components/ProcessSteps/src/_StepHeading.scss
Fix rare cases of lots of overflowing texts
> fix: fix rare cases of lots of overflowing texts

- .github/dependabot.yml
Change interval from weekly -> monthly
> build: change dependabot schedule

- components/Pagination/src/Pagination.tsx
- components/Table/src/TableCell.tsx
- components/Table/src/TableHeader.tsx
- components/Table/src/index.scss
- packages/storybook/src/css/Table.stories.mdx
- packages/storybook/src/react/Table.stories.tsx
Link toegevoegd aan een table cell/header
> Table cell/header href

- components/Table/package.json
- components/Table/src/TableCell.tsx
- components/Table/src/TableHeader.tsx
- pnpm-lock.yaml
Link mogelijkheid toegevoegd aan TableCell en TableHeader om een link component mee te geven.
> Add link prop to tablecell/header

- components/ButtonLink/README.md
- components/ButtonLink/package.json
- components/ButtonLink/src/index.scss
- components/ButtonLink/src/index.tsx
- components/ButtonLink/tsconfig.json
- packages/storybook/package.json
- packages/storybook/src/react/ButtonLink.stories.tsx
- pnpm-lock.yaml
Heb een externe link nodig die er uit ziet als een button voor de button in de taken. Weet niet helemaal of dit het juiste is. Misschien goed om hier nog even over te sparren.
> Utrecht Button Link

- components/Hero/src/index.scss
- proprietary/Components/src/denhaag/hero.tokens.json
Added font-weight token for the link in the hero
Added font-weight style for the link in the hero
> feat(hero): modified hero link

- components/Action/tokens.json
- components/Sidenav/tokens.json
- packages/storybook/config/DesignTokensBlock.tsx
- packages/storybook/config/index.d.ts
- packages/storybook/config/preview.tsx
- packages/storybook/package.json
- packages/storybook/src/react/Action.stories.tsx
- packages/storybook/src/react/Sidenav.stories.tsx
- pnpm-lock.yaml
- proprietary/Components/style-dictionary.config.js
- style-dictionary.config.json
Work in progress van mij en Matijs om de Design Tokens JSON met de "Copy JSON" button toe te voegen aan de Storybook van Den Haag. Deze feature zit al in de Storybook van gemeente Utrecht, maar we willen 'm vanuit het kernteam beschikbaar maken voor meer teams. Daarom verhuizen we de componenten naar de theme's repo, vanwaar we 'm kunnen installeren in elke Storybook van organisaties die white label components maken.
PR is nog afhankelijk van nl-design-system/themes#519 en moet nog even gerebased worden.
> docs: add example design tokens JSON to Sidenav and Action

- components/Divider/README.md
- components/Divider/src/index.tsx
- components/Icons/README.md
- components/List/README.md
- components/Sheet/README.md
Heb aantal oude verwijzingen naar Material UI uit de docs verwijderd.
> Remove couple of doc refs

- components/TextInput/package.json
- components/TextInput/src/index.scss
- components/TextInput/src/index.tsx
- components/TextInput/src/pra-textbox.scss
- pnpm-lock.yaml
Added a copy of the PRA Textbox to work around issues with CSP unsafe-inline/nonce and the PRA package size.
> fix: work around csp and treeshaking issue by adding copy of component

- components/Menu/src/menu-button.scss
- components/Menu/src/menu.scss
- proprietary/Components/src/denhaag/menu-button.tokens.json
- proprietary/Components/src/denhaag/menu.tokens.json
> style(menu): reduce tokens

- .stylelintrc.json
- components/CardNews/src/index.scss
- components/CardNews/src/stories/bem.stories.mdx
- components/CardNews/src/storybook.scss
> style(card-news-featured): add featured variant

- components/CardNews/src/index.scss
- components/CardNews/src/stories/bem.stories.mdx
> style(news-card): add meta

- components/CardNews/src/index.scss
Closes multiple www.denhaag.nl branches :D 
closes #905  #1141  #1142 #1146 #1275 #1673 #1621
> style(card): adjust card-styles

- components/Alert/src/index.scss
- components/AnchorCollapse/src/index.scss
- components/Conditions/src/index.scss
- components/ImageBanner/src/index.scss
- components/Typography/src/paragraph.scss
Closing some other www denhaag branches aswel ;-)
closes #1516 #1620 #1673
> Www denhaag nl after release

- .github/dependabot.yml
> chore: improve dependabot config

- components/Button/package.json
- components/Image/src/index.scss
- components/InlineCarousel/src/index.scss
- components/InlineCarousel/src/stories/bem.stories.mdx
Reduce duplication..
closes: #1620
> feat(inline-carousel): reduce duplicate code

- components/LinkGrid/src/index.scss
> style(link-grid): disable mouse click events on decorative item

- components/Container/src/index.scss
- components/Container/src/stories/bem.stories.mdx
> style(container): add svi instead of 100%

- components/Hero/src/index.scss
Indent routing hero same as the content.
Cleanup old branches:
closes #1620 #1706
> style(hero): set indent same as page content

- packages/web-components/case-card/src/element.ts
- packages/web-components/case-card/src/index.html
Updates the card element 
- No more html string building
- Add property changed behaviour
- Implement fallback lang based on doc
- Add default icon as fallback
> chore: refactor card element

- components/Procedure/src/StepList.scss
- components/Procedure/src/index.scss
- components/Procedure/src/stories/bem.stories.mdx
add more specificity so that it actually overwrites the <ol> and added top margin when under paragraph
> GDH-1524 style(procedure): add and fix margins for procedure
